### PR TITLE
Fix: Adapt method is disposed before being completed

### PR DESCRIPTION
**Pull request by mashe**
## Description
replace .flatMapLatest with .flatMap to avoid adapt to be disposed before being completed
related issue #183 

## Checklist

- [x] this PR is based on develop or a 'develop related' branch
- [x] the commits inside this PR have explicit commit messages
- [ ] the Jazzy documentation has been generated (if needed -> Jazzy RxFlow)

### CODE REVIEW

**Comment by mashe** [comment]
@twittemb Hey! Do you have any thoughts about this?

**Comment by twittemb** [comment]
Hi @mashe, sorry for the delay.

Could you tell me a bit more about your use case, what kind of long operation do you want to perform in the `adapt` function ?

I'm just wondering if `adapt` is well suited to handle long operations. Initially the goal was to be able to present an intermediate View before navigating (like a view for authentication).

If you perform a long operation in the function, how is the use feedback ? you display a progress spinner ?

thanks.

PS: I'm just trying to remember exactly why it was `flatMapLatest` in the first place :-)

**Comment by mashe** [comment]
@twittemb in my particular case I am using `adapt` to dismiss presented ViewController before presenting another one. This is a long operation. And another `Step` is received while dismissing that should update SplitViewController selection.

Since `adapt` returns `Single`, the only difference between `.flatMap` and `.flatMapLatest` is to skip an uncompleted Step or not. I do not think it is designed to skip Steps in mind. From my experience `.flatMapLatest` is used by default and I would write exactly the same way. So it looks pretty safe to use `.flatMap` instead, or am I missing something?

**Comment by mashe** [comment]
@twittemb any new thoughts?

**Comment by mashe** [comment]
@twittemb ping

**Review by twittemb — APPROVED** [review]
LGTM

**Pull request merged**
