### PR TITLE
Handle UIPageViewController child's steps not being handled after first visit

### PR DESCRIPTION
**Pull request by lihao6485**
## Description
https://github.com/RxSwiftCommunity/RxFlow/issues/117

## Checklist

- [x] this PR is based on develop or a 'develop related' branch
- [x] the commits inside this PR have explicit commit messages
- [x] the Jazzy documentation has been generated (if needed -> Jazzy RxFlow)

### CODE REVIEW

**Comment by twittemb** [comment]
Hi @lihao6485.

Thanks for the PR, this is interesting. I'd like to propose another way though.

I'd make no modification to Flow. In my mind a Flow should not be aware of its parent's presentable if possible.

We could leave Flow as it is for now. But we could:

- add a new parameter to FlowContributor: FlowContributor.contribute(withNextPresentable: Presentable, withNextStepper: Stepper, allowStepWhenNotPresented: Bool = false, allowStepWhenDismissed: Bool = false)
- change to implementation of FlowCoordinator (a little but like you already did) to take the new parameter into account.

What do you think ?

**Comment by lihao6485** [comment]
@twittemb Yes, I agree with you that Flow should not be aware of its parent presentable if possible. 

I have updated my PR with your suggestion by adding `allowStepWhenDismissed` but not sure I added `allowStepWhenDismissed` as a new parameter for the FlowCoordinator's `coordinate` is it fine?

**Comment by twittemb** [comment]
@lihao6485 

Thanks for the update. I think it's nice. Could you add an example of UIPageViewController in the demo App ? once it is done I think we are ok.

thanks.

**Comment by lihao6485** [comment]
@twittemb I have added a new tab item called `Trending` with a `UIPageViewController` inside to demo the scenario.

**Comment by twittemb** [comment]
LGTM. Thanks a lot for your contribution.

**Comment by rynecheow** [comment]
@twittemb Can we release this hotfix on a version where iOS 11 is still supported? The sudden drop of iOS 11 was unexpected and we can't move away yet...

**Comment by twittemb** [comment]
@rynecheow unfortunately there must have been a mistake somewhere. Minimum iOS version should be 9.0

I will fix that tomorrow.

Thanks for pointing that out.

**Comment by twittemb** [comment]
@rynecheow 

I have republished the v2.11.0 with a minimum iOS version 9.0.

**Comment by rynecheow** [comment]
Thanks @twittemb !

**Pull request merged**
