### PR TITLE
Add tech talk reference

### PR DESCRIPTION
**Pull request by MortyMerr**
I gave a tech talk on quite famous conference AppsConf about RxFlow in production. Sadly, it was in Russian. However, if you don't mind, I would like to add reference on it. Just for sharing experience with other users.

### CODE REVIEW

**Comment by twittemb** [comment]
@MortyMerr can you rebase this on develop on make develop being the target of the PR please ?

also, is there a simple way of adding English subtitles to the video ?

**Comment by MortyMerr** [comment]
@twittemb I changed base to developer.
Sadly I don't know the way to quickly add subtitles (only YouTube automatically generated). If you think that adding Russian resource to international repo is impolite, please feel free to close this PR :)

**Comment by twittemb** [comment]
No I don't think adding Russian resources to an international repo is impolite at all. I just want to find a way to make it accessible for everyone. Perhaps you could annotate your slides with English sentence and we could publish the video + the annontated slides.

**Comment by MortyMerr** [comment]
Honestly, I don't think it makes too much sense. Both slides & voice are in Russian. Even with subtitles & annotated slides I don't think it will be comfortable for English people to watch that video. However, it can be very useful for Russians :)

**Comment by benjohnde** [comment]
I don't know how it works, but there exists a possibility to add auto-translations. I friend of mine did it, will feedback ASAP (potentially upcoming Wednesday) on how to do that. He really enjoyed your talk btw :) @swift2geek

**Comment by MortyMerr** [comment]
@benjohnde thanks man, appreciate that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twittemb** [comment]
@benjohnde Do you have an update about the automatic translations ?

thanks.

**Comment by benjohnde** [comment]
Sry I have forgotton this issue. I just asked him: sadly he had to add translations for at least one language, the rest is then auto-translated via Google. There is the possibility to add the first language via speech recognition. You should be able to do so with the [YouTube Studio](https://studio.youtube.com). For what's worth it: the feature is called "YouTube's auto caption". Hopefully that gives you a hint in the right direction @MortyMerr!

**Comment by MortyMerr** [comment]
Hey guys, I dig a little bit more in this. It looks like Youtube can autogenerate subtitles for any language. First, you should press the "subtitles" button to see original (Russian) subtitles and then select Settings->Subtitles->Translate->select_your_language
I checked the quality of these subtitles and it looks good for me. Please tell me if can do anything else to get this merged :)

image

**Comment by twittemb** [comment]
Thanks for your insight. I will try the feature and get back to you ASAP.

**Comment by twittemb** [comment]
Hi @MortyMerr 

Could you amend your commit to add the instructions in the README to add generated subtitles please ?

**Comment by MortyMerr** [comment]
Hi @twittemb 
I added instruction. I am not sure how to style it properly. IMO now this link with instruction takes to much space in Readme. Do you have any idea how to improve its appearance? Maybe move to the bottom of readme?

**Comment by twittemb** [comment]
Thanks @MortyMerr

**Pull request merged**
