### PR TITLE
Implementation for HasDisposeBag -> disposeBag Setter

### PR DESCRIPTION
**Pull request by Dimentar**
## Description

Added setter for disposeBag in HasDisposeBag protocol.
Credits for [RxSwiftCommunity/NSObject-Rx](https://github.com/RxSwiftCommunity/NSObject-Rx)

## Checklist

- [x] this PR is based on develop or a 'develop related' branch
- [x] the commits inside this PR have explicit commit messages
- [ ] the Jazzy documentation has been generated (if needed -> Jazzy RxFlow)

### CODE REVIEW

**Comment by twittemb** [comment]
Hi @Dimentar 

Thanks for your PR. I'm not sure I see your point here. In fact I did the HasDisposeBag protocol in NSObject-Rx a few months ago, but I don't see the need to have a setter here.

HasDisposeBag is used only internally in RxFlow.

Perhaps your point is "What happens if I want to use RxFlow and NSObject-Rx in my project ?". Indeed, there will be 2 HasDisposeBag implementation and it could be an issue.

Instead of adding a setter to HasDisposeBag, I suggest we rename HasDisposeBag in RxFlow so it does not collide with NSObject-Rx.

Does that make sens to you ?

**Comment by twittemb** [comment]
Hi @Dimentar 

I really think we should rename HasDisposeBag, just to avoid collisions where NSObject-Rx. I don't want to add a setter because this is not that purpose of the framework to handle disposeBags. Doing so, you will be able to use both RxFlow and NsObject-Rx.

I suggest you modify your PR to rename the protocol in "ProvideDisposeBag" or something like that.

Is this ok with you ?

**Comment by Dimentar** [comment]
Hi @twittemb 
It's OK for me to rename the protocol (even if it can be referenced by **RxFlow.HasDisposeBag**) and the property (which gives us more problems for name collision with **NSObject-Rx**).
I will do a  refactory.

**Comment by twittemb** [comment]
Hi @Dimentar 

Can you elaborate on your point about name collisions with NSObject-Rx ?

**Comment by Dimentar** [comment]
Hi @twittemb 
Sorry my mistake, no name collisions after module name specification `NSObject_Rx.HasDisposeBag`
Take a look at the snippet:
```swift
import UIKit
import RxSwift
import RxFlow
import NSObject_Rx

class FirstViewController: UIViewController { // UIViewController already conforms to Presentable -> HasDisposeBag
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        
        disposeBag = DisposeBag() // Error: Cannot assign to property: 'disposeBag' is a get-only property
    }
}

class SecondViewController: UIViewController, NSObject_Rx.HasDisposeBag { // Working
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        
        disposeBag = DisposeBag()  // Working
    }
}
```

Like you already said `HasDisposeBag ` is declared **public** only because of _swift language_ which not supports _public protocol_ inheritance from _internal protocol_. There is no clean and simple solution (for now only subclassing). 
However, I will try searching the solution.
Regarding **HasDisposeBag** collision, we can leave without renaming and close PR with no merging, because the simplest solution is to specify module name `NSObject_Rx.HasDisposeBag`.
Completely understand your point of view, the purpose of this library is not to handle disposeBags.
Thanks.

**Comment by twittemb** [comment]
Hi @Dimentar 

Thanks for you feedback. I got it right, RxFlow is not about handling disposeBag but I understand your concern about name collision. Using NSObject_Rx.HasDisposeBag is an acceptable solution.

Thanks again and see you soon on other PRs 👍

**Pull request closed without merging**
