### PR TITLE
SPM docs & badge

### PR DESCRIPTION
**Pull request by MortyMerr**
## Description
Added SPM docs & badge. I guess next release would be `2.5.0`, so I added example with this version https://github.com/RxSwiftCommunity/RxFlow/issues/127

## Checklist
- [x] this PR is based on develop or a 'develop related' branch
- [x] the commits inside this PR have explicit commit messages
- [ ] the Jazzy documentation has been generated (if needed -> Jazzy RxFlow)

### CODE REVIEW

**Comment by MortyMerr** [comment]
@twittemb I am not sure about circleCI fail. As I can see you moved to github actions, so probably CircleCI integration should be removed?

**Comment by twittemb** [comment]
Hi @MortyMerr 

I've removed CircleCI. Can you trigger another CI run please ?

**Comment by MortyMerr** [comment]
@twittemb still can see circleci here. What's the point to trigger CI again? Github CI is green

**Comment by twittemb** [comment]
I just wanted to see if the CircleCI step would disappear.

**Comment by twittemb** [comment]
Thanks for your contribution

**Pull request merged**
